---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
data:
  postgres_uri: {{ .Values.env.postgresUri | quote }}
  report_path: {{ .Values.env.reportPath | quote }}
  log_path: {{ .Values.env.logPath | quote }}