apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.vault.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  vault_token: {{ .Values.global.vault.vaultToken | quote }}